name: prime-yard-apartments-app

services:
  api:
    build:
      context: ./server
      target: production
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - prime-yard-apartments-app
    restart: unless-stopped

  web:
    build:
      context: ./site
      target: production
    networks:
      - prime-yard-apartments-app
    depends_on:
      - api
    restart: unless-stopped

  nginx:
    image: nginx:1.27.4-alpine
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - prime-yard-apartments-app
    depends_on:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERT_EMAIL} -d ${DOMAIN} --agree-tos
    networks:
      - prano-app
    depends_on:
      - nginx

networks:
  prime-yard-apartments-app:
    driver: bridge
